import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const hook = readFileSync(new URL('../src/hooks/useHandBrew.js', import.meta.url), 'utf8');
const modal = readFileSync(new URL('../src/components/HandBrewModal.jsx', import.meta.url), 'utf8');
const timer = readFileSync(new URL('../src/components/BrewTimer.jsx', import.meta.url), 'utf8');
assert.match(hook, /generateV60HotWithFallback/);
assert.match(hook, /V60 regeneration unavailable/);
const v60Branch = hook.slice(hook.indexOf("if (device === 'v60' && !recipe)"), hook.indexOf("if (!recipe) {", hook.indexOf("if (device === 'v60' && !recipe)")));
assert.match(v60Branch, /V60 regeneration unavailable/);
assert.doesNotMatch(v60Branch, /generateHandBrewRecipe/);
assert.match(hook, /handBrewIcedLoading/);
assert.match(hook, /handBrewIcedError/);
assert.match(hook, /activeRequestRef\.current = null/);
assert.match(hook, /requestedFingerprintRef\.current !== fingerprint/);
assert.match(hook, /useEffect\(\(\) => \{[\s\S]*mountedRef\.current = true;[\s\S]*mountedRef\.current = false;/, 'hand-brew lifecycle must recover its mounted flag after the React Strict Mode effect replay');
const requestLifecycle = hook.slice(hook.indexOf('const handleBrewHandBrew'), hook.indexOf('const regenerateIced'));
assert.ok(requestLifecycle.indexOf('setHandBrewResearch(requestResearch)') < requestLifecycle.indexOf('if (!forceRegenerate && cached)'));
assert.match(requestLifecycle, /let research = requestResearch/);
const closeLifecycle = hook.slice(hook.indexOf('const closeHandBrewModal'), hook.indexOf('const persistDose'));
assert.match(closeLifecycle, /clearTimeout\(doseDebounceRef\.current\)/);
assert.match(modal, /isDeterministicV60Hot/);
assert.match(modal, /Retry iced recipe/);
assert.match(modal, /min=\{12\} max=\{30\}/);
assert.match(modal, /normalizeRecipePhases\(scaledRecipe\)/);
assert.match(modal, /Expected drawdown:/);
assert.doesNotMatch(modal, /Target drawdown:/);
assert.match(modal, /Drawdown tip/);
assert.match(modal, /const hotTimerSteps = useMemo\(\(\) => buildTimerSteps\(displayRecipe\)/);
assert.match(modal, /const timerReady = Boolean\(hotTimerSteps\)/);
const hotView = modal.slice(modal.indexOf('{/* Hot recipe display */}'), modal.indexOf('{/* Iced mode view */}'));
const icedView = modal.slice(modal.indexOf('{/* Iced mode view */}'));
assert.doesNotMatch(hotView, /icedRecipe\.techniqueLabel|icedRecipe\.reasoning/);
assert.match(icedView, /icedRecipe\.techniqueLabel/);
assert.match(icedView, /icedRecipe\.sourceLineage\?\.adaptation/);
assert.match(timer, /dialogRef\.current\?\.focus\(\)/);
assert.match(timer, /inert=\{completionOverlayVisible \? true : undefined\}/);
assert.match(timer, /onDismiss=\{onClose\}/);
assert.match(timer, /expected drawdown/);
assert.match(timer, /finish on drawdown/);
assert.doesNotMatch(timer, /guide finish/);
console.log('handbrew V60 cutover consumer contract passed (no GPT dose fallthrough, independent iced error path)');
