import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const hook = readFileSync(new URL('../src/hooks/useHandBrew.js', import.meta.url), 'utf8');
const modal = readFileSync(new URL('../src/components/HandBrewModal.jsx', import.meta.url), 'utf8');
const transformer = readFileSync(new URL('../src/lib/flashBrewTransform.js', import.meta.url), 'utf8');
const quickRecipe = readFileSync(new URL('../src/components/QuickRecipeFlow.jsx', import.meta.url), 'utf8');
const rotation = readFileSync(new URL('../src/tabs/RotationTab.jsx', import.meta.url), 'utf8');

assert.match(hook, /generateKalitaIcedWithFallback/);
assert.match(hook, /KALITA_ICED_SOURCE_REGISTRY_VERSION/);
assert.match(hook, /validateKalitaIcedCandidate/);
assert.match(hook, /queueLatestRecipeWrite/);
assert.match(hook, /createKeyedLatestWriteQueue/);
assert.match(hook, /canUseCachedHotRecipe/);
assert.match(hook, /resolveIcedRetryConfiguration/);
assert.match(hook, /handleKalitaIcedChillingMethodChange/);
assert.match(hook, /preservedChillingMethod/);
assert.match(hook, /attachHandBrewBeanId/);
assert.match(hook, /chillingMethod/);
assert.match(hook, /onRegenerate:[\s\S]*chillingMethod: handBrewRecipe\?\.device === 'kalita'/);
assert.match(hook, /Could not save the chilling method\. Your previous recipe is still selected\./);
assert.match(hook, /iced cache repair persistence failed/);
assert.match(hook, /setHandBrewIcedRecipe\(null\)[\s\S]*setHandBrewIcedLoading\(true\)/);
assert.match(modal, /isDeterministicKalitaHot\(displayRecipe\)/);
assert.match(modal, /icedRecipe\?\.icedModeLabel/);
assert.match(modal, /Wave \$\{icedRecipe\.kalitaSize\} · Iced/);
assert.match(modal, /KalitaIcedChillingSwitch/);
assert.match(modal, /Brew over ice/);
assert.match(modal, /Chill after/);
assert.match(modal, /Recommended starting point for this Wave size and dose\./);
assert.match(modal, /Using the conservative fallback for this Wave size and dose\./);
assert.match(modal, /minHeight: 44/);
assert.match(modal, /Final beverage water depends on how much chill ice melts/);
assert.doesNotMatch(modal, /Final beverage-water target: \{icedRecipe\.finalBeverageWaterTargetGrams\}g/);
assert.match(transformer, /Deterministic hot Kalita candidates require the independent iced Kalita adapter/);
assert.match(quickRecipe, /handBrewIcedRecipes: \{ \[icedForSave\.device \|\| 'v60'\]: icedForSave \}/);
assert.match(quickRecipe, /beanData\.handBrewIcedRecipes = \{ \[icedRecipe\.device \|\| 'v60'\]: icedRecipe \}/);
assert.match(quickRecipe, /handBrew\.attachHandBrewBeanId\(newId\)/);
assert.match(rotation, /if \(handBrewIcedRecipes\) beanData\.handBrewIcedRecipes = handBrewIcedRecipes/);
console.log('handbrew Kalita iced cutover contract passed');
