import assert from 'node:assert/strict';
import { generateV60Recipe } from '../src/lib/v60Adapter.js';
const large = generateV60Recipe({}, { dose: 30 });
assert.match(large.steps[0].action, /60g/);
assert.match(large.steps[1].action, /300g/);
assert.match(large.steps[2].action, /stir.*swirl/i);
assert.doesNotMatch(large.steps[2].action, /do not swirl|off the paper/i);
const rao = generateV60Recipe({ energyTendency: 'higher', finesRisk: 'low' }, { dose: 20 });
assert.match(rao.steps[0].action, /aggressively.*spin/i);
assert.match(rao.steps[1].action, /gentle.*spin/i);
assert.match(rao.steps[2].action, /second gentle.*spin/i);
const heart = generateV60Recipe({ finesRisk: 'high' }, { dose: 20 });
assert.match(heart.steps[0].action, /40–50g|45g/i);
assert.match(heart.steps[0].action, /do not stir/i);
assert.match(heart.steps[1].action, /slow center pour.*without a final stir/i);
assert.equal(heart.sourceLineage.parameterSources.agitation, 'v60-adaptation-bounded-v1');
const adapted = generateV60Recipe({ cupDirection: { body: 'supported' } }, { dose: 18 });
assert.equal(adapted.sourceLineage.changedFields.includes('ratio'), true);
assert.equal(adapted.sourceLineage.parameterSources.ratio, 'v60-adaptation-bounded-v1');
console.log('v60 technique copy/provenance passed (large, Rao, Heart, incomplete Kurasu adaptation)');
