import assert from 'node:assert/strict';
import { generateV60Recipe } from '../src/lib/v60Adapter.js';
import { generateV60IcedRecipe } from '../src/lib/v60IcedAdapter.js';
const oneCupExact = generateV60Recipe({}, { dose: 15 });
assert.equal(oneCupExact.sourceLineage.status, 'original');
assert.equal(oneCupExact.sourceLineage.changedFields.includes('dose'), false);
const oneCupScaled = generateV60Recipe({}, { dose: 16 });
assert.equal(oneCupScaled.sourceLineage.status, 'scaled');
assert.ok(oneCupScaled.sourceLineage.changedFields.includes('dose'));
assert.equal(oneCupScaled.sourceLineage.parameterSources.dose, 'user-configuration');
assert.equal(oneCupScaled.sourceLineage.parameterSources.water, 'v60-dose-scaling-v1');
const largeExact = generateV60Recipe({}, { dose: 30 });
assert.equal(largeExact.sourceLineage.status, 'original');
const heartExact = generateV60Recipe({ finesRisk: 'high' }, { dose: 22 });
assert.equal(heartExact.sourceLineage.status, 'original');
const partnersExact = generateV60IcedRecipe({}, { dose: 20 });
assert.equal(partnersExact.sourceLineage.status, 'original');
const partnersScaled = generateV60IcedRecipe({}, { dose: 18 });
assert.equal(partnersScaled.sourceLineage.status, 'scaled');
assert.equal(partnersScaled.sourceLineage.parameterSources.hotWater, 'v60-iced-dose-scaling-v1');
const kurasuExact = generateV60IcedRecipe({ source: 'Kurasu staged iced' }, { dose: 16 });
assert.equal(kurasuExact.sourceLineage.status, 'adapted');
console.log('V60 dose-scaling provenance passed (exact and scaled hot/iced source doses)');
