import assert from 'node:assert/strict';
import { generateV60IcedFallback, generateV60IcedRecipe, validateV60IcedCandidate } from '../src/lib/v60IcedAdapter.js';
import { generateV60Recipe } from '../src/lib/v60Adapter.js';
const small = generateV60IcedRecipe({}, { dose: 16 });
assert.equal(small.technique, 'pulse-67-33-flash');
assert.equal(validateV60IcedCandidate(small).valid, true);
assert.equal(small.steps[0].timeSeconds, 0);
assert.equal(small.hotWaterGrams + small.initialBrewIceGrams, small.finalBeverageWaterTargetGrams);
const large = generateV60IcedRecipe({}, { dose: 30, grinder: 'other' });
assert.equal(large.technique, 'classic-60-40-flash');
assert.equal(large.grindSize.setting, null);
const kurasu = generateV60IcedRecipe({ source: 'Kurasu staged iced' }, { dose: 16 });
assert.equal(kurasu.technique, 'kurasu-staged-flash');
const fallback = generateV60IcedFallback({ dose: 20 }, 'invalid-evidence');
assert.equal(fallback.fallback, true);
assert.equal(generateV60Recipe({}, { dose: 16 }).mode, 'hot');
assert.notEqual(small.technique, generateV60Recipe({}, { dose: 16 }).technique);
assert.equal(validateV60IcedCandidate({ ...small, initialBrewIceGrams: small.initialBrewIceGrams + 1 }).valid, false);
console.log('iced V60 adapter passed (families, custom grinder, fallback, hot rejection)');
